title: Project Actuator
author: Corridore407 (at gmail)
description: > # this means to ignore newlines until "show_exerpts:"
  A journey through project actuator, an arduino powered switch
  panel built to enhance the experience of playing Elite Dangerous.
show_excerpts: false # set to true to show excerpts on the homepage

# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %B %d, %Y"

  # generate social links in footer
  social_links:
    github: westonnovelli

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-seo-tag
