// GAME COMMAND TO KEYBINDINGS CONFIGURED HERE
// EXAMPLE:
//     #define _GALAXY_MAP_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
//     #define _GALAXY_MAP KEY_1

#define _SUPERCRUISE_MOD KEY_MOD_LCTRL
#define _SUPERCRUISE KEY_J

#define _HYPERSPACE_MOD KEY_MOD_LALT
#define _HYPERSPACE KEY_J

#define _JUMP_DISENGAGE KEY_J

#define _ZERO_THROTTLE_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _ZERO_THROTTLE KEY_F1

#define _FIVE_ZERO_FORWARD_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _FIVE_ZERO_FORWARD KEY_F2

#define _FIVE_ZERO_REVERSE_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT | KEY_MOD_LALT
#define _FIVE_ZERO_REVERSE KEY_F2

#define _SEVEN_FIVE_FORWARD_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _SEVEN_FIVE_FORWARD KEY_F3

#define _SEVEN_FIVE_REVERSE_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT | KEY_MOD_LALT
#define _SEVEN_FIVE_REVERSE KEY_F3

#define _ONE_ZERO_ZERO_FORWARD_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _ONE_ZERO_ZERO_FORWARD KEY_F4

#define _ONE_ZERO_ZERO_REVERSE_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT | KEY_MOD_LALT
#define _ONE_ZERO_ZERO_REVERSE KEY_F4

#define _JETTISON_CARGO_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _JETTISON_CARGO KEY_DOT

#define _SELF_DESTRUCT_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT | KEY_MOD_LALT
#define _SELF_DESTRUCT KEY_KPPLUS

#define _TOGGLE_CARGO_SCOOP KEY_HOME
#define _TOGGLE_LANDING_GEAR KEY_L
#define _TOGGLE_LIGHTS KEY_INSERT
#define _TOGGLE_HARDPOINTS KEY_U
#define _TOGGLE_ORBIT_LINES KEY_EQUAL

#define _TOGGLE_ROTATONAL_CORRECTION_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _TOGGLE_ROTATONAL_CORRECTION KEY_F9

#define _TOGGLE_NIGHT_VISION_MOD KEY_MOD_LCTRL
#define _TOGGLE_NIGHT_VISION KEY_B

#define _SWITCH_HUD_MODE KEY_M

#define _OPEN_GALAXY_MAP_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _OPEN_GALAXY_MAP KEY_1

#define _OPEN_SYSTEM_MAP_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _OPEN_SYSTEM_MAP KEY_2

#define _NEXT_SYSTEM_IN_ROUTE_MOD KEY_MOD_LCTRL | KEY_MOD_LSHIFT
#define _NEXT_SYSTEM_IN_ROUTE KEY_N

#define _DISMISS_RECALL_SHIP KEY_END
